import "../styles/globals.css";
import Navbar from "../src/components/Navbar/Navbar";
import Head from "next/head";
import { useState } from "react";

function MyApp({ Component, pageProps }) {
  const [lang, setLang] = useState("en_US");

  return (
    <>
      <Head>
        <title>List Champions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setLang={setLang} lang={lang} />
      <Component lang={lang} setLang={setLang} {...pageProps} />
    </>
  );
}

export default MyApp;
